FROM node:20
WORKDIR /usr/src/app

# 设置淘宝镜像源
RUN npm config set registry https://registry.npmmirror.com


COPY package*.json ./
# 使用淘宝镜像安装全局包
RUN npm install -g rivalz-node-cli --registry=https://registry.npmmirror.com

COPY . .
CMD ["rivalz", "run"]

# 执行命令 docker build -t rivalz-node-cli .
# 执行命令 docker run -it rivalz-node-cli
# 